{"0": "0", "1": "1", "2": "2", "3": "3", "4": "4", "5": "5", "6": "6", "7": "7", "8": "8", "9": "9", "space": " ",
 "exclam": "!", "quotedbl": "\"", "numbersign": "#", "dollar": "$", "percent": "%", "ampersand": "&", "quoteright": "'",
 "parenleft": "(", "parenright": ")", "asterisk": "*", "plus": "+", "comma": ",", "minus": "-", "period": ".",
 "slash": "/", "colon": ":", "semicolon": ";", "less": "<", "equal": "=", "greater": ">", "question": "?",
 "at": "@", "A": "A", "B": "B", "C": "C", "D": "D", "E": "E", "F": "F", "G": "G", "H": "H", "I": "I", "J": "J",
 "K": "K", "L": "L", "M": "M", "N": "N", "O": "O", "P": "P", "Q": "Q", "R": "R", "S": "S", "T": "T", "U": "U",
 "V": "V", "W": "W", "X": "X", "Y": "Y", "Z": "Z", "bracketleft": "[", "backslash": "\\", "bracketright": "]",
 "asciicircum": "^", "underscore": "_", "quoteleft": "`", "a": "a", "b": "b", "c": "c", "d": "d", "e": "e", "f": "f",
       "g": "g", "h": "h", "i": "i", "j": "j", "k": "k", "l": "l", "m": "m", "n": "n", "o": "o", "p": "p", "q": "q", "r": "r",
 "s": "s", "t": "t", "u": "u", "v": "v", "w": "w", "x": "x", "y": "y", "z": "z",
 "braceleft": "{", "bar": "|", "braceright": "}", "asciitilde": "~",
 "Begin": "", "End": "", "Next": "", "Prior": "", "Down": "", "Right": "", "Up": "", "Left": "",
 "Home": "", "Multi_key": "", "Escape": "", "Sys_Req": "", "Scroll_Lock": "",
 "Pause": "", "Return": "\n", "Clear": "", "Linefeed": "\r", "Tab": "\t",
 "BackSpace": "\b", "Select": "", "Print": "", "Execute": "", "Insert": "",
       "Undo": "", "Redo": "", "Menu": "", "Find": "", "Cancel": "", "Help": "", "Break": "",
 "Num_Lock": "", "KP_Space": " ", "KP_Tab": "\t", "KP_Enter": "\n", "KP_F1": "", "KP_F2": "", "KP_F3": "",
 "KP_F4": "", "KP_Multiply": "*", "KP_Add": "+", "KP_Separator": "", "KP_Subtract": "-", "KP_Decimal": ".",
 "KP_Divide": "/", "KP_0": "0", "KP_1": "1", "KP_2": "2", "KP_3": "3", "KP_4": "4", "KP_5": "5", "KP_6": "6",
 "KP_7": "7", "KP_8": "8", "KP_9": "9", "KP_Equal": "=", "F1": "", "F2": "", "F3": "", "F4": "", "F5": "", "F6": "",
 "F7": "", "F8": "", "F9": "", "F10": "", "Shift_L": "", "Shift_R": "", "Control_L": "", "Control_R": "",
       "Caps_Lock": "", "Shift_Lock": "", "Alt_L": "", "Alt_R": "", "Delete": ""}
